backend_repo_url: "https://github.com/cyber-mya/book-review-app.git"
backend_app_port: 3001
db_host: "myabookreview-db.mysql.database.azure.com"
db_user: "mysqladmin"
db_password: "DevSecureDBPassword123!"
db_name: "book_review_db"
jwt_secret: "your_jwt_secret"
allowed_origins: "http://4.147.187.166:3000"
